#!/bin/sh

cd `dirname $0`

for dot in dot.*; do
  target=../.`echo $dot | sed 's/^dot.//'`
  if [ ! -e $target ]; then
    ln -vs .dotfiles/$dot $target
  fi
done

lesskey

for file in cshrc zshrc zshenv; do
  if [ ! -f ../.$file ]; then
    echo "Creating skeletal ~/.$file"
    echo "source ~/.$file.base" > ../.$file
  fi
done

[ -d ../bin        ] || mkdir ../bin
[ -d ../bin/shared ] || ln -s ../.dotfiles/bin-shared ../bin/shared
