#!/bin/sh

prog=`basename $0`
dir=`mktemp -d --tmpdir $prog.XXXXX`
google-chrome --no-first-run --no-make-default-browser --disable-metrics \
              --homepage=about:blank --user-data-dir=$dir "$@" >/dev/null 2>&1
rm -rf $dir
