#!/bin/sh

cat > "$1" <<'EOF'
#!/usr/bin/perl

use strict;
use warnings;
use Getopt::Std;
use File::Basename;

my $prog = basename($0);
my %opt;
getopts('h', \%opt);
usage() if $opt{h};
sub usage {
  die <<EOU;
usage: $prog
EOU
}

EOF

chmod 775 "$1"
exec $EDITOR "$1"
