#!/bin/sh -e
#
# moves a single commit from main onto a git-wf feature branch
#

if [ $# -ne 1 ]; then
  echo "usage: `basename $0` feature-name"
  exit 1
fi

BRANCH=oops-`date +%s`

git checkout -b $BRANCH
git checkout main
git reset --hard HEAD^
git wf start $1
git reset --hard $BRANCH
git branch -d $BRANCH
git push -f
