#!/usr/bin/env python
"""
Roll "dice" to see how many hides are in each room: 0-5

Total should equal 12
"""

from random import randint
import sys

def roll_rooms(num_rooms: int = 4):
    if num_rooms < 3:
        raise ValueError("Can't add up to 12 with fewer than 3 rooms")

    while True:
        nums = [randint(0, 5) for _ in range(num_rooms)]
        if sum(nums) == 12:
            return nums

if __name__ == "__main__":
    num_rooms = int(sys.argv[1]) if len(sys.argv) > 1 else 4
    print(roll_rooms(num_rooms))
