#! /bin/sh
#
# stderr-iff-err - run given cmd, caching its stderr, only outputting it
#                  on a non-zero exit, and passing through its exit code
#

prog=`basename $0`
if [ $# -eq 0 -o "$1" = -h ]; then
  echo "usage: $prog cmd [args]" >&2
  exit 1
fi

tmp=`mktemp -t $prog.XXXXX`
"$@" 2>$tmp
status=$?

if [ $status -ne 0 ]; then
  cat $tmp >&2
fi

rm $tmp
exit $status
