#!/usr/bin/env python3
#
# total-times - find hh:mm:ss sections in input and report total time
#

import datetime as dt
import re
import sys

HMS_PAT = re.compile(r"\b(\d\d):(\d\d):(\d\d(?:\.\d+)?)\b")
S_PAT = re.compile(r"\b(?P<n>\d+)(?P<unit>[mμn]?s)\b")

total = 0.0
for line in sys.stdin:
  if m := HMS_PAT.search(line):
    h, m, s = map(float, m.groups())
    total += h * 3600 + m * 60 + s
  elif m := S_PAT.search(line):
    n = int(m.group('n'))
    unit = m.group('unit')
    if unit == 'ms':
      n /= 1_000
    elif unit == 'μs':
      n /= 1_000_000
    elif unit == 'ns':
      n /= 1_000_000_000
    total += n

print(dt.timedelta(seconds=total))
