#!/bin/sh -e
#
# viencsh - create or edit encrypted shell scripts
#           NOTE: may leave unencrypted tmpfiles around on failure!
#

PROG=`basename $0`
temp=`getopt -o h -n $PROG -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$temp"

usage () {
  cat <<EOF >&2
usage: $PROG file
EOF
  exit 1
}

while true; do
  case $1 in
    -h) usage ;;
    --) shift ; break ;;
     *) echo 'internal error' >&2 ; exit 1 ;;
  esac
done

[ $# -eq 1 ] || usage

FILE=$1
TMP=`mktemp -t $PROG.XXXXX.sh`
cleanup () {
  rm -f $TMP
  exit ${1:-1}
}
trap cleanup INT

if [ -f $FILE ]; then
  awk 'NR==1,/#START/{next}/^EOF$/,NR==0{next}{print}' $FILE \
    | base64-decode | openssl bf-cbc -d -md md5 -provider legacy -provider default > $TMP
else
  touch $TMP
fi

HEADER=$(cat <<EOS
#!/bin/bash -e
set -o pipefail

base64-decode <<EOF | openssl bf-cbc -d -md md5 -provider legacy -provider default | bash -e #START
EOS
)

if ${EDITOR:-editor} $TMP; then
  PAYLOAD=`openssl bf-cbc -e -in $TMP -provider legacy -provider default | base64`
  if ! [ -z "$PAYLOAD" ]; then
    (echo "$HEADER" ; echo "$PAYLOAD" ; echo EOF) > $FILE
    chmod a+x $FILE
    cleanup 0
  fi
fi

cleanup 1
