#!/bin/bash -e

PROG="${0##*/}"

waitSecs=15

usage () {
  cat <<EOF >&2
usage: $PROG [-s secs] [some-npm-pkg]
       -s: how many secs to wait between checks (default: $waitSecs)
       some-npm-pkg: which to wait for (defaults to
                     ./package.json's name property; requires jq)
EOF
  exit 1
}

while getopts "hs:" opt; do
  case "$opt" in
    h) usage ;;
    s) waitSecs=$OPTARG ;;
    *) echo 'internal error' >&2 ; exit 1 ;;
  esac
done
shift $((OPTIND-1))

if [ $# -eq 0 ]; then
  pkg=`jq -r .name package.json`
elif [ $# -eq 1 ]; then
  pkg="$1"
else
  usage
fi

startSecs=`date '+%s'`
curVersion=`npm v "$pkg" version`

echo -n "$curVersion..."

while true; do
  sleep $waitSecs
  newVersion=`npm v "$pkg" version`
  if [ $curVersion != $newVersion ]; then
    endSecs=`date '+%s'`
    echo "$newVersion ($(($endSecs - $startSecs))s)"
    exit 0
  fi
  echo -n .
done
