#!/bin/sh

XPRA_ROOT=/home/dbushong/build/parti-all-0.0.5/install
export PYTHONPATH=$XPRA_ROOT/lib/python

host=`basename $0`
pidfile=`mktemp -t xpra-attach.pid.XXXXX`
start-stop-daemon -b -m -p $pidfile -a $XPRA_ROOT/bin/xpra -S attach ssh:$host:1
pid=`cat $pidfile`
rm $pidfile
(( gnome-terminal -t "ssh $host" --disable-factory --geometry 80x45 -e "ssh -t -C $host screen -D -R" ; kill $pid ) &)
